// <auto-generated />
using System;
using MagicVilla_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_Api.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            DateCreation = new DateTime(2024, 3, 12, 6, 52, 58, 182, DateTimeKind.Local).AddTicks(9345),
                            DateUpdated = new DateTime(2024, 3, 12, 6, 52, 58, 182, DateTimeKind.Local).AddTicks(9387),
                            Detail = "Vistas al mar",
                            Fee = 0.0,
                            Name = "Villa Marina",
                            Occupants = 5,
                            SquareMeters = 50,
                            UrlImage = ""
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            DateCreation = new DateTime(2024, 3, 12, 6, 52, 58, 182, DateTimeKind.Local).AddTicks(9395),
                            DateUpdated = new DateTime(2024, 3, 12, 6, 52, 58, 182, DateTimeKind.Local).AddTicks(9397),
                            Detail = "Vistas a la piscina",
                            Fee = 0.0,
                            Name = "Villa Piscina",
                            Occupants = 4,
                            SquareMeters = 45,
                            UrlImage = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
